=== toxin98/analog/schemas/main.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Photography Analog Metadata Schema",
  "type": "object",
  "required": ["id", "film", "camera", "date", "development", "note"],
  "additionalProperties": false,
  "properties": {

    "id": {
      "type": "string",
      "pattern": "^[0-9]{4}$",
      "description": "Roll unique ID (e.g., 0001)"
    },

    "film": { "$ref": "film.schema.json" },

    "camera": { "$ref": "camera.schema.json" },

    "date": {
      "type": "object",
      "required": ["started", "finished"],
      "additionalProperties": false,
      "properties": {
        "started": { "type": "string", "format": "date" },
        "finished": { "type": "string", "format": "date" }
      }
    },

    "development": {
      "type": "object",
      "required": ["lab", "process", "digitization"],
      "additionalProperties": false,
      "properties": {
        "lab": { "$ref": "lab.schema.json" },
        "process": { "$ref": "process.schema.json" },
        "digitization": { "$ref": "digitization.schema.json" }
      }
    },

    "note": {
      "type": "string"
    }

  }
}

=== toxin98/analog/metadata/0014.json
{
  "id": "0014",
  "film": "Reflx Lab 800T",
  "camera": "Olympus MJU I",
  "date": {
    "started": "2026-08-16",
    "finished": "2026-08-16"
  },
  "development": {
    "lab": "大连, 感光实验室",
    "process": "C-41",
    "digitization": {
      "method": "scanner",
      "brand": "Noritsu",
      "model": "HS-1800"
    }
  },
  "note": ""
}

=== toxin98/analog/metadata/0001.json
{
  "id": "0001",
  "film": "Kodak 5219",
  "camera": "Pentax KX",
  "date": {
    "started": "2022-10-03",
    "finished": "2023-01-14"
  },
  "development": {
    "lab": "上海, 菲林公园",
    "process": "ECN-2",
    "digitization": {
      "method": "scanner",
      "brand": "Noritsu",
      "model": null
    }
  },
  "note": ""
}

=== toxin98/analog/metadata/0006.json
{
  "id": "0006",
  "film": "Kodak Gold 200",
  "camera": "Pentax KX",
  "date": {
    "started": "2024-08-17",
    "finished": "2025-04-29"
  },
  "development": {
    "lab": "南京, 南京丰悦",
    "process": "C-41",
    "digitization": {
      "method": "scanner",
      "brand": "Fujifilm",
      "model": "Frontier SP-3000"
    }
  },
  "note": ""
}

=== toxin98/analog/metadata/0007.json
{
  "id": "0007",
  "film": "Foma FOMAPAN 400",
  "camera": "Pentax MX",
  "date": {
    "started": "2026-01-11",
    "finished": "2026-04-09"
  },
  "development": {
    "lab": "北京, 1350Film",
    "process": "D-76",
    "digitization": {
      "method": "scanner",
      "brand": "Noritsu",
      "model": "HS-1800"
    }
  },
  "note": "试机的，测光准的，但是这机子有些小毛病，快门速度转盘太紧，计数器不走，快门有时会卡住使得机器一直测光，扳手完全关闭也能触发测光，偶尔反光板不下落"
}

=== toxin98/analog/metadata/0013.json
{
  "id": "0013",
  "film": "Reflx Lab 800T",
  "camera": "Pentax MX",
  "date": {
    "started": "2026-08-16",
    "finished": "2026-08-16"
  },
  "development": {
    "lab": "大连, 感光实验室",
    "process": "C-41",
    "digitization": {
      "method": "scanner",
      "brand": "Noritsu",
      "model": "HS-1800"
    }
  },
  "note": ""
}

=== toxin98/analog/metadata/0004.json
{
  "id": "0004",
  "film": "Kodak ColorPlus 200",
  "camera": "Pentax KX",
  "date": {
    "started": "2023-05-28",
    "finished": "2024-08-17"
  },
  "development": {
    "lab": "南京, 金陵银盐馆",
    "process": "C-41",
    "digitization": {
      "method": "scanner",
      "brand": "Fujifilm",
      "model": "Frontier SP-3000"
    }
  },
  "note": "2020年过期胶卷"
}

=== toxin98/analog/metadata/0010.json
{
  "id": "0010",
  "film": "Kodak Gold 200",
  "camera": "Pentax LX",
  "date": {
    "started": "2026-04-28",
    "finished": "2026-05-03"
  },
  "development": {
    "lab": "上海, Irohas Photo",
    "process": "C-41",
    "digitization": {
      "method": "scanner",
      "brand": "Fujifilm",
      "model": "Frontier SP-500"
    }
  },
  "note": ""
}

=== toxin98/analog/metadata/0002.json
{
  "id": "0002",
  "film": "Kodak 5213",
  "camera": "Pentax KX",
  "date": {
    "started": "2023-01-14",
    "finished": "2023-05-28"
  },
  "development": {
    "lab": "上海, F212沸点",
    "process": "ECN-2",
    "digitization": {
      "method": "scanner",
      "brand": "Noritsu",
      "model": null
    }
  },
  "note": ""
}
